/* eslint-disable max-len */

import React, { Component } from 'react';
import Page from '../../templates/page';
import { H1, H2 } from '../../atoms/headline';
import Link from '../../atoms/link';
import P from '../../atoms/paragraph';

export default class About extends Component {
  render() {
    return (
      <Page>
        <H1>{ 'Privacy Policy' }</H1>
        <H2>{ 'What information do we collect?' }</H2>
        <P>{ 'We collect information from you when you register on our site or fill out a form.' }</P>
        <P>{ 'When registering on our site, as appropriate, you may be asked to enter your username and e-mail address. You may, however, visit our site anonymously.' }</P>
        <H2>{ 'What do we use your information for?' }</H2>
        <P>{ 'Any of the information we collect from you may be used in one of the following ways:' }</P>
        <P>{ '- To improve our website' }</P>
        <P><i>{ '(we continually strive to improve our website offerings based on the information and feedback we receive from you)' }</i></P>
        <H2>{ 'How do we protect your information?' }</H2>
        <P>{ 'We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.' }</P>
        <H2>{ 'Do we use cookies?' }</H2>
        <P>{ 'Yes' }</P>
        <P><i>{ '(cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information)' }</i></P>
        <P>{ 'We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.' }</P>
        <H2>{ 'Do we disclose any information to outside parties?' }</H2>
        <P>{ 'We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.' }</P>
        <H2>{ 'Third party links' }</H2>
        <P>{ 'Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.' }</P>
        <H2>{ 'California Online Privacy Protection Act Compliance' }</H2>
        <P>{ 'Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.' }</P>
        <P>{ 'As part of the California Online Privacy Protection Act, all users of our site may make any changes to their information at anytime by logging into their account and going to the "Settings" page.' }</P>
        <H2>{ 'Web analysis with Google Analytics' }</H2>
        <P>{ 'This website uses Google Analytics, a web analysis service of Google Inc. (Google). Google Analytics uses cookies, i.e. text files stored on your computer to enable analysis of website usage by you. Information generated by the cookie about your use of this website is usually transmitted to a Google server in the United States and stored there. In case of activated IP anonymization on this website, however, your IP address is previously truncated by Google within member states of the European Union or in other states which are party to the agreement on the European Economic Area. Only in exceptional cases is a full IP address transmitted to a Google server in the United States and truncated there. On behalf this website\'s owner, Google will use this information to evaluate your use of the website, compile reports about website activities, and provide the website\'s operator with further services related to website and Internet usage. The IP address sent from your browser as part of Google Analytics is not merged with other data by Google. You can prevent storage of cookies by appropriately setting your browser software; in this case, however, please note that you might not be able to fully use all functions offered by this website. In addition, you can prevent data generated by the cookie and relating to your use of the website (including your IP address) from being collected and processed by Google, by downloading and installing a browser plug-in from the following link: https://tools.google.com/dlpage/gaoptout?hl=en.' }</P>
        <P>{ 'This website uses Google Analytics with the extension "anonymizeIP()", IP addresses being truncated before further processing in order to rule out direct associations to persons.' }</P>
        <H2>{ 'Online Privacy Policy Only' }</H2>
        <P>{ 'This online privacy policy applies only to information collected through our website and not to information collected offline.' }</P>
        <H2>{ 'Your Consent' }</H2>
        <P>{ 'By using our site, you consent to our web site privacy policy.' }</P>
        <H2>{ 'Changes to our Privacy Policy' }</H2>
        <P>{ 'If we decide to change our privacy policy, we will post those changes on this page, and update the Privacy Policy modification date below.' }</P>
        <P>{ 'This policy was last modified on April 02, 2018.' }</P>
        <H2>{ 'Contacting Us' }</H2>
        <P>{ 'If there are any questions regarding this privacy policy you may contact us using the information below.' }</P>
        <P>{ 'Email: ' }<Link href="mailto:hello@booky.io">{ 'hello@booky.io' }</Link></P>
        <P>{ 'This policy is powered by Free Privacy Policy and Rhino Support ' }<Link href="https://www.rhinosupport.com/">{ 'help desk software' }</Link>{ '.' }</P>
      </Page>
    );
  }
}

/* eslint-disable max-len */
