export default {
  user: {
    loggedIn: false,
    name: '',
    email: '',
    title: '',
    new: true,
    premium: false,
    settings: {
      blurEffect: true,
      darkMode: false,
      dashboardsStyle: 'sidebar',
      maxWidth: false,
      navigationBarColor: 0,
      openLinksInNewTab: true,
      pinned: true,
      preserveEditMode: true,
      stickyHeader: true,
      stickyToolbar: true,
      autofillBookmarkNames: true,
      colorScheme: 0,
      defaultDashboardId: null,
      enableNotes: true
    }
  },
  dashboards: {
    items: [],
    pending: false,
    error: null
  },
  categories: [],
  sidebar: {
    open: false
  },
  toolbar: {
    currentlySticky: true
  },
  modal: {
    modal: null,
    open: false,
    data: {}
  },
  search: {
    keyword: '',
    results: {
      'total': 30,
      'offset': 0,
      'limit': 50,
      'dashboards': [
        {
          'id': 324234234,
          'name': 'Dashboard 1',
          'categories': [
            {
              'id': 45567567,
              'name': 'Category 1',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            },
            {
              'id': 79789789,
              'name': 'Category 2',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            },
            {
              'id': 457567,
              'name': 'Category 3',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            }
          ]
        },
        {
          'id': 78778897,
          'name': 'Dashboard 2',
          'categories': [
            {
              'id': 45567567,
              'name': 'Category 1',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            },
            {
              'id': 79789789,
              'name': 'Category 2',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            },
            {
              'id': 457567,
              'name': 'Category 3',
              'color': 'color3',
              'bookmarks': [{'id': 317547, 
                'name': 'rosa Ferienwohnung in Zadar mit Riesenpool', 
                'url': 'http:\/\/www.traum-ferienwohnungen.de\/46957.htm', 
                'position': 1, 
                'categoryId': 1727, 
                'clicked': 21, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 34446, 
                'name': 'another booky', 
                'url': 'https:\/\/booky.io', 
                'position': 2, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 6, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAWBJREFUOI2dkb1OAkEUhQ\/DLMIubILAYkJiQ2PiI9DxAjYmFjYEK6M0mhhNjMEXsKGW2BkTE+MLbEchhTY2JhoNCQWIElb2T2CxUEZ2+XHl62buPWfOvePpH276ABwZ3V6m+qEm4IJESKj6qfcKwB4FcPzUVPbdCAf8PLSdDIte0jI\/N\/4jdhhlSEMzYrMaGN1egMwqHkCHD2IqjcjKGggvoNOoo1YsAADi2Ry4qARLU\/F2fQGlJDON53FrvQ8AXFTCYv7E5m5pKgCA8ILtvpLfQadR\/66xKBFpJB7hhRGxs5cZWLr6x7TjYQZm5dk22ySUkgz94f43zXDx9byI9m0Z\/NIyxFSaxbc0FUpJhll5QfvuxmbIluiEi0qIZ3MAgFqxwJbmhI69BWzfOEkMAFTgaFvtdIOTTKbhp16dLAT506ldU0iEhDMK4CAZFgPvurnaNMx5N0JxzteK8f5LALtfhg96izYcJpYAAAAASUVORK5CYII='}, {'id': 31682, 
                'name': 'np krka', 
                'url': 'http:\/\/ ', 
                'position': 3, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 456456, 
                'name': 'Google', 
                'url': 'http:\/\/google.de', 
                'position': 4, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 33970, 
                'name': 'Google sheet', 
                'url': '\/\/google.de', 
                'position': 5, 
                'categoryId': 1727, 
                'clicked': 8, 
                'note': '', 
                'faviconId': 9, 
                'favicon': 'data:image\/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8\/9hAAAABHNCSVQICAgIfAhkiAAAAglJREFUOI2Nk99L02EUxj\/vNkthRdToFxLNJqaJESYVXtSN3ZS1CqMM6qKLQKJ\/oPsF3eV1F1HRBrVcGV4FdRPeJUK0oeYaUmyzRbOxpvtuTxd+v7atIA+ci\/e8z3nOe57zHmgwSQFJEUkzksq2z9ixtkZ8bSKSxvR\/i0r6Z3LCQRRfxZS7claZ7u3KHPApd3lQxfE67rhDYmyCMSCo5RLfh89QSc6A2w1WebWCZwNaLtLU08fWxy+cus+NMRecniVJi+dOKtPfrUzPLhUij2TNz8lKzqkQfqjs0XZV8j8a2\/FjiyPrQ1iZI61Kd+yUtZBahxSSpDC2wrImA1qZQMXo6HqTJSnhAfwAys9h3NA80FsnsLn1kw6vWTv\/qkCwy829ay0AbZ46sMBUGkZUY9uaDW4DtQgXkATwbG6nBEwsxOtHPLqJRMhLIuTl4mEPhbLY53M51\/Mu4D1AevcdDi6e4NRUhM9LX\/6qns3D\/UmLchX6O9cePmW0+j0\/AQzErvO1mOVbpcjdQyMca+3FZVxMp6e5\/SaFL32DPT6LJzdbHAK\/85GiwPlSdYXg+Agfl1J4jJuyKghoMi5kCuzQcd4OhWjZCMAzY8yQQwAQB\/YDvJx9zYPZGO9ycapA35YAVwOnudQ56FSOA13G\/JmOsw\/Rdcz+qRqXqU51yS8prNXlWrE9Ycf2NuJ\/A6uf5JCErH2FAAAAAElFTkSuQmCC'}, {'id': 31768, 
                'name': 'Im Urlaub wie zu Hause f\u00fchlen', 
                'url': 'https:\/\/www.casamundo.de\/ferienhaus-ferienwohnung\/2596350?days=7\u0026persons=2\u0026split19=14352\u0026split20=14283\u0026start=2015-08-23', 
                'position': 6, 
                'categoryId': 1727, 
                'clicked': 17, 
                'note': '', 
                'faviconId': 0, 
                'favicon': 'default'}, {'id': 735114, 
                'name': '\u00f6okdsfj\u00f6odfs', 
                'url': 'l\u00f6odfljg', 
                'position': 7, 
                'categoryId': 1727, 
                'clicked': 0, 
                'note': '', 
                'faviconId': 8, 
                'favicon': 'default'}]
            }
          ]
        }
      ]
    }
  }
};
